spring:
 cloud:
  gateway:
   discovery:
    locator:
     enabled: true
   routes: 
    - id: code-dtl-service
      uri: lb://CODE-DTL-SERVICE
      predicates:
      - Path=/api/code-dtl/**
    - id: locs-service
      uri: lb://LOCS-SERVICE
      predicates:
      - Path=/api/locs/**
    - id: sups-service
      uri: lb://SUPS-SERVICE
      predicates:
      - Path=/api/sups/**    
