spring:
 datasource:
  url: jdbc:h2:file:/cloud/code_db
  driverClassName: org.h2.Driver
  username: cloud
  password: cloud
 h2:
  console.enabled: true
  console.path: /h2-console
  console.settings.trace: false
  console.settings.web-allow-others: false
jpa:
  database-platform: org.hibernate.dialect.H2Dialect
  defer-datasource-initialization: true
